2016-03-08 11:11:53+0300 [-] Log opened.
2016-03-08 11:11:53+0300 [-] PBServerFactory starting on 13333
2016-03-08 11:11:53+0300 [-] Starting factory <twisted.spread.pb.PBServerFactory instance at 0x027C5800>
2016-03-08 11:11:54+0300 [-] Starting off the system
2016-03-08 11:12:26+0300 [-] Daily Thread initiating messenger
2016-03-08 11:12:26+0300 [-] this is the type extension
2016-03-08 11:12:26+0300 [-] extension has been disabled
2016-03-08 11:12:26+0300 [-] this is the type renewal
2016-03-08 11:12:26+0300 [-] renewal has been disabled
2016-03-08 11:12:26+0300 [-] this is the type clients
2016-03-08 11:12:26+0300 [-] clients has been disabled
2016-03-08 11:12:26+0300 [-] this is the type newinvoice
2016-03-08 11:12:26+0300 [-] Unhandled error in Deferred:
2016-03-08 11:12:26+0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "runserver.py", line 565, in <module>
	    main()
	  File "runserver.py", line 560, in main
	    task.LoopingCall(manager.daily_messenger).start(86400)
	  File "d:\python27\lib\site-packages\twisted\internet\task.py", line 173, in start
	    self()
	  File "d:\python27\lib\site-packages\twisted\internet\task.py", line 218, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	  File "D:\Projects\CMS\server1.3\cron.py", line 353, in daily_messenger
	    message_controller.central_command()
	  File "D:\Projects\CMS\server1.3\cron.py", line 197, in central_command
	    if isinstance(message_creator(key, details, recipients, message), list):
	  File "D:\Projects\CMS\server1.3\cron.py", line 95, in message_creator
	    if max_invoice_number:
	exceptions.UnboundLocalError: local variable 'max_invoice_number' referenced before assignment
	
2016-03-08 11:12:48+0300 [-] Hourly Thread initiating messenger
2016-03-08 11:12:48+0300 [-] 0 messages waiting to be sent
